# Generated by Django 5.0.6 on 2024-06-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama')),
            ],
            options={
                'db_table': 'states',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'kategori'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nama'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nama')),
                ('owner', models.CharField(max_length=100, verbose_name='owner')),
                ('emaiil', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='phone')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='postal code')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'db_table': 'shops',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.state')),
            ],
            options={
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
    ]
