# Generated by Django 5.0.6 on 2024-06-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shop_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['id'], 'verbose_name': 'toko', 'verbose_name_plural': 'Toko'},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='emaiil',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='alamat'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.city', verbose_name='kota'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='pemilik'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='no.telp/hp'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='kode pos'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.state', verbose_name='provinsi'),
        ),
    ]
