# Generated by Django 5.0.6 on 2024-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shop_options_rename_emaiil_shop_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('weight', models.FloatField(verbose_name='weight')),
                ('price', models.FloatField(verbose_name='price')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='store.category', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
                'ordering': ['created_at'],
            },
        ),
    ]
